# This is a basic workflow to help you get started with Actions

name: testing
env:
  APPLICATION_NAME    : "Simple-Bot"
  SHA_DIGEST : "${{ github.sha }}"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Printing info message
      - name: Printing Info
        run:  |
          echo "Appication name: ${{ env.APPLICATION_NAME }}"
          echo "Commit digest: ${{ env.SHA_DIGEST }}"

      # Installing script requirements & running repository
      - name: Installing script requirements
        run: |
          pip install -r requirements.txt
          python main.py

      # Reading output SQL database 
      - name: Reading output SQL database
        run:  python db_reader.py

        
